CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "last_name" varchar(30) NOT NULL,
  "email" varchar(60) NOT NULL,
  "password" varchar(50) NOT NULL,
  "age" int NOT NULL,
  "role_fk" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_fk" int NOT NULL,
  "description" varchar(50) NOT NULL,
  "level_fk" int NOT NULL,
  "teacher_fk" int NOT NULL,
  "categorie_fk" int NOT NULL,
  "course_url_fk" int NOT NULL
);

CREATE TABLE "courses_level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(25) NOT NULL
);

CREATE TABLE "courses_teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher" varchar(50) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "course_title" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(70) NOT NULL
);

CREATE TABLE "course_url" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(200) NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_fk") REFERENCES "courses_teacher" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_fk") REFERENCES "courses_level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categorie_fk") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("course_url_fk") REFERENCES "course_url" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("title_fk") REFERENCES "course_title" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_fk") REFERENCES "roles" ("id");

INSERT INTO "roles" (name) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO "course_title" (title) VALUES ('Curso de React JS'), ('Introducción a las bases de datos');

INSERT INTO "courses_level" (level) VALUES ('Principiante'), ('Intermedio'), ('Avanzado');

INSERT INTO "courses_teacher" (teacher) VALUES ('Andres'), ('Brenda');

INSERT INTO "categories" (name) VALUES ('Desarrollo Frontend'), ('Desarrollo Backend');

INSERT INTO "course_url" (url) VALUES ('https://www.youtube.com/watch?v=4UZrsTqkcW4'), ('https://www.youtube.com/watch?v=9S1iM5t5SjQ');

INSERT INTO "users" (name, last_name, email, password, age, role_fk) VALUES ('Noe', 'Hernandez', 'noe@academlo.com', 'noe1234', 20, 1);

INSERT INTO "users" (name, last_name, email, password, age, role_fk) VALUES ('Ian', 'Rosas', 'ian@academlo.com', 'ian1234', 28, 2);

INSERT INTO "courses" (title_fk, description, level_fk, teacher_fk, categorie_fk, course_url_fk) VALUES (1, 'En este curso aprenderas React JS desde 0', 1, 1, 1, 1);

INSERT INTO "courses" (title_fk, description, level_fk, teacher_fk, categorie_fk, course_url_fk) VALUES (2, 'En este curso aprenderas las bases de datos', 1, 2, 2, 2);



